### PR TITLE
Fix font locking of defintions with metadata

### PR DESCRIPTION
**Pull request by kommen**
Partly addresses #42 

Extracted from #43 as discussed there.

### CODE REVIEW

**Comment by bbatsov** [comment]
Shouldn't we also add some unit tests for this?

**Comment by kommen** [comment]
@bbatsov yes, of course. I'll see if I can port the font lock test infrastructure over from closure-mode.

**Comment by kommen** [comment]
@bbatsov what do you think about this as a first step for font lock test coverage?

**Comment by bbatsov** [comment]
It's fine by me. Thanks for working on this!

**Pull request merged**
