### PR TITLE
Merge clojure-mode tests into clojure-ts-mode

### PR DESCRIPTION
**Pull request by kommen**
Attempt to address #25: Bring over the clojure-mode test suit and preserve history and contributors.

This was done:

Prepare a clone of clojure-mode with just contents of test/

```
$ git clone --no-checkout https://github.com/clojure-emacs/clojure-mode.git ~/work/clojure-mode-tests-only
$ cd ~/work/clojure-mode-tests-only
$ git filter-branch --subdirectory-filter test -- --all
```

Add it to clojure-ts-mode and merge it
```
$ cd ~/work/clojure-ts-mode
$ git remote add clojure-mode-tests ~/work/clojure-mode-tests-only
$ git fetch clojure-mode-tests
$ git merge --allow-unrelated-histories clojure-mode-tests/master
```

### CODE REVIEW

**Comment by bbatsov** [comment]
Seems like a step in the right direction to me.

**Comment by kommen** [comment]
Got the build green but ignoring all the merged clojure-mode test files for now in eldev: So as discussed in https://github.com/clojure-emacs/clojure-ts-mode/issues/25#issuecomment-2448484562, this just adds the test suite without actually running any of those tests.

One thing I was wondering: maybe put the clojure-mode-* tests into a different directory to avoid any confusion?

**Comment by bbatsov** [comment]
Yeah, I think that would be prudent and would make it easier to keep track of what needs to be updated for `clojure-ts-mode`.

**Comment by kommen** [comment]
@bbatsov done. Anything else you feel we should tackle before getting this merged?

**Comment by bbatsov** [comment]
Nope, I think we're all good here.

**Pull request merged**
